# Install pre-commit hooks via: pre-commit install
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.5.0
  hooks:
  - id: double-quote-string-fixer
  - id: end-of-file-fixer
  - id: fix-encoding-pragma
  - id: mixed-line-ending
  - id: trailing-whitespace

# modernizer: make sure our code-base is Python 3 ready
- repo: https://github.com/python-modernize/python-modernize.git
  rev: v0.9rc0
  hooks:
  - id: modernize
    exclude: ^docs/
    args:
      - --write
      - --nobackups

# yapf = yet another python formatter
- repo: https://github.com/pre-commit/mirrors-yapf
  rev: v0.30.0
  hooks:
  - id: yapf
    name: yapf
    types: [python]
    args: ['-i']

- repo: local
  hooks:
  # pylint: static code analysis
  - id: pylint
    name: pylint
    entry: pylint
    types: [python]
    language: system
