language: python
python:
  - 2.7
  - 3.6

install: pip install -e .[test]
script: pytest

os:
  - linux
dist: trusty
addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
